### PR TITLE
Add basic SSHA hash tool

### LINKED ISSUE #6: LDAP password creation utility
Settings LDAP passwords via CLI is complicated. The Korga frontend should contain a utility page where users can enter their desired password and get printed out an SSHA hash which they can send to a server administrator.

See [SSHA in Java](https://stackoverflow.com/a/42490862/7075733) for reference.

### PR DESCRIPTION
**Pull request by daniel-lerch**
This pull request provides a very basic tool to create SSHA hashes for OpenLDAP in the browser (resolves #6). I know that this algorithm is insecure, yet this tool will be great help until Korga can handle OpenID Connect.

### CODE REVIEW

**Comment by daniel-lerch** [comment]
On our church's server this implementation has been successfully tested.

**Comment by Beniox** [comment]
- [ ] Don't create a hash if you input nothing/ the input is blank

Optional:
- [ ] Add password requirements e.g min 8 characters
- [ ] Add a show password icon
- [ ] Add a copy to clipboard button

**Comment by Beniox** [comment]
It looks much better now
One little thing, it would be better to show a short summary of requirements for the password instead to say that it is insecure, if the input is blank (it does not look good if you are greeted with that message when you open the website)

**Comment by daniel-lerch** [comment]
Now I have a more friendly greeting message. Specifying exact requirements for a password however is difficult.

I spent more than an hour on research for password validation libraries. Dropbox's [zxcvbn](https://github.com/dropbox/zxcvbn) seems to be the best library available but is not maintained anymore and neither works with TypeScript nor with Webpack. ideal-password which I'm using now is far away from perfect but still better than a simple 8 character check.

**Review by Beniox — APPROVED** [review]

**Pull request merged**
